# Generated by Django 4.2.26 on 2025-12-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='instructores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20, unique=True)),
                ('tipe_document', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extrangeria'), ('TI', 'Tarjeta de identidad'), ('PAS', 'Pasaporte')], max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=200)),
                ('level_education', models.CharField(choices=[('BACH', 'Bachiller'), ('TECN', 'Tecnico'), ('ING', 'Ingeniero'), ('MAST', 'Maestro'), ('PREGRA', 'Pregrado'), ('POSTGR', 'Postgrado'), ('MAESTRIA', 'Maestria'), ('DOCTORADO', 'Doctorado')], max_length=10)),
                ('speciality', models.CharField(max_length=100)),
                ('years_experience', models.IntegerField()),
                ('state', models.BooleanField(default=True)),
                ('date_boding', models.DateField()),
                ('date_record', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
