# Generated by Django 4.2.26 on 2025-12-04 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('aprendices', '0001_initial'),
        ('instructores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Inscripción')),
                ('state', models.CharField(choices=[('INS', 'Inscrito'), ('ACT', 'Activo'), ('DES', 'Desertor'), ('GRA', 'Graduado'), ('SUS', 'Suspendido')], default='INS', max_length=3, verbose_name='Estado en el Curso')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Nota Final')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Aprendiz por Curso',
                'verbose_name_plural': 'Aprendices por Curso',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código del Curso')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Curso')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Fecha de Finalización')),
                ('schedule', models.CharField(max_length=100, verbose_name='Horario')),
                ('classroom', models.CharField(max_length=50, verbose_name='Aula/Ambiente')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Cupos Máximos')),
                ('state', models.CharField(choices=[('PRO', 'Programado'), ('INI', 'Iniciado'), ('EJE', 'En Ejecución'), ('FIN', 'Finalizado'), ('CAN', 'Cancelado'), ('SUS', 'Suspendido')], default='PRO', max_length=3, verbose_name='Estado del Curso')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('aprendices', models.ManyToManyField(related_name='cursos', through='cursos.AprendizCurso', to='aprendices.aprendices', verbose_name='Aprendices')),
                ('instructor_coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_coordinados', to='instructores.instructores', verbose_name='Instructor Coordinador')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Rol en el Curso')),
                ('assignment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructores.instructores')),
            ],
            options={
                'verbose_name': 'Instructor por Curso',
                'verbose_name_plural': 'Instructores por Curso',
                'unique_together': {('teacher', 'course')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='instructors',
            field=models.ManyToManyField(related_name='cursos_impartidos', through='cursos.InstructorCurso', to='instructores.instructores', verbose_name='Instructores'),
        ),
        migrations.AddField(
            model_name='curso',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa', verbose_name='Programa de Formación'),
        ),
        migrations.AddField(
            model_name='aprendizcurso',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso'),
        ),
        migrations.AddField(
            model_name='aprendizcurso',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aprendices.aprendices'),
        ),
        migrations.AlterUniqueTogether(
            name='aprendizcurso',
            unique_together={('student', 'course')},
        ),
    ]
